### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by mubed** [bbadjari/stylecopcli#1]
Are there no releases for this tool, so that I can use them without having to compile it myself?

**Comment by bbadjari** [comment]
I haven't created any on GitHub yet, but you can get all of the releases at the old SourceForge site:

https://sourceforge.net/projects/stylecopcli/

**Comment by mubed** [comment]
OK, thanks.

**Comment by bbadjari** [comment]
Added latest release including latest binaries.
