### ISSUE TITLE
How can I replace StyleCop dlls?

### ISSUE THREAD

**Issue by mubed** [bbadjari/stylecopcli#2]
Is there a way to tell StyleCopCLI to use the newer versions of StyleCop dlls instead of the built-in ones?

**Comment by bbadjari** [comment]
You can try downloading the latest release from the official StyleCop site located here: http://stylecop.codeplex.com

Note that it may or may not be backwards compatible with the assemblies used by StyleCop CLI. If not, some work will need to be done to support them.

**Comment by bbadjari** [comment]
Just upgraded the StyleCop binaries to 4.7.54.0.
