### ISSUE TITLE
-recursiveSearch flag

### ISSUE THREAD

**Issue by IvanRibakov** [bbadjari/stylecopcli#7]
Is it possible to use recursiveSearch flag without specifying solution or project file, i.e. just search recursively in the folder where StyleCopCLI is being called from?

Reason I need this is because...well, I don't have access to solution or project files (Unity3D quirks).

**Comment by bbadjari** [comment]
What are you looking to search for recursively? Keep in mind that you can use wildcards and simply search for C# source files (i.e. *.cs).

**Comment by IvanRibakov** [comment]
I'm searching for `*.cs` files but I don't have `.csproj` file. In your example you seem to only use `-r` flag together with `-proj`. 

What I would like to be able to do is to get all `.cs` files from multiple **nested** folders using only `-r` flag:
`StyleCopCLI -r`

Is that the intended use for `-r` flag? Documentation "-r : Recursively search subdirectories for files to analyze." suggests it is but I was unable to make it work.

**Comment by bbadjari** [comment]
The `-r` flag can be used with other combinations of commands.

You should be able to use the following command-line arguments: `StyleCopCLI -cs *.cs -r`
